services:
  registration:
    build: .
    container_name: registration-botomat
    restart: unless-stopped
    ports:
      - "3749:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
