version: '3.8'

services:
  registration:
    build: .
    container_name: registration-botomat
    restart: unless-stopped
    ports:
      - "3080:80"
    networks:
      - web

networks:
  web:
    external: true
