services:
  registration:
    build: .
    container_name: registration-botomat
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3850
